# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure-pipelines

pool:
  name: webMethods Build Server
  demands:
    - agent.name -equals dev-wm-02-vm
steps:
- task: BatchScript@1
  inputs:
    filename: 'C:\SoftwareAG_107\install\bin\setenv.bat'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      set ANT_HOME=C:/SoftwareAG_107/common/lib/ant
      %ANT_HOME%/bin/ant -f build.xml -DpathCWD=%cd% %*