# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure-pipelines

pool:
  name: webMethods Build Server
  demands:
    - agent.name -equals dev-wm-02-vm
steps:
- task: CmdLine@2
  inputs:
    script: 'ant build'
#- task: Ant@1
#  inputs:
#    buildFile: 'build.xml'
#    options: 
#    targets: 'build'
#    publishJUnitResults: false
#    antHomeDirectory: 'C:\SoftwareAG_107\common\lib\ant'
#    javaHomeOption: 'Path'
#    jdkUserInputDirectory: 'C:\SoftwareAG_107\jvm\jvm'