# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure-pipelines

pool:
  name: webMethods Build Server
  demands:
    - agent.name -equals dev-wm-02-vm
steps:
- task: Ant@1
  displayName: Ant Build
  inputs:
    buildFile: 'build.xml'
    options: 
    targets: 'build'
    publishJUnitResults: false
    antHomeDirectory: 'C:\SoftwareAG_107\common\lib\ant'
    javaHomeOption: 'Path'
    jdkUserInputDirectory: 'C:\SoftwareAG_107\jvm\jvm'
- task: Ant@1
  displayName: Ant Deploy
  inputs:
    buildFile: 'build.xml'
    options: 'DtestISPassword=manage DdeployerPassword=manage'
    targets: 'deploy'
    publishJUnitResults: false
    antHomeDirectory: 'C:\SoftwareAG_107\common\lib\ant'
    javaHomeOption: 'Path'
    jdkUserInputDirectory: 'C:\SoftwareAG_107\jvm\jvm'